#!/bin/bash
set -e
cd "$(dirname "$0")"

echo "🔨 Generating SDK from webspec..."

# Generate into temp directory
TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

cargo run --manifest-path ../webspec/Cargo.toml -- generate \
    --spec ../funpay-spec/spec/funpay.yaml \
    --target rust \
    --output "$TMPDIR"

# Copy generated files
mkdir -p src/generated
cp "$TMPDIR/src/"*.rs src/generated/

# Fix crate:: → super:: for submodule paths
sed -i 's/use crate::/use super::/g' src/generated/*.rs

# Generate mod.rs
cat > src/generated/mod.rs << 'EOF'
// @generated by webspec — DO NOT EDIT

pub mod models;
pub mod parser;
pub mod client;
pub mod error;
EOF

echo "✅ Generated into src/generated/"
echo "   Run 'cargo build' to compile"
