// @generated by specgen — DO NOT EDIT

use reqwest::Client;
use crate::error::FunPayError;
use crate::models::*;
use crate::parser::Parser;

pub const DEFAULT_BASE_URL: &str = "https://funpay.com";

pub struct FunPayClient {
    pub client: Client,
    pub base_url: String,
}

impl FunPayClient {
    pub fn new() -> Result<Self, FunPayError> {
        Self::with_base_url(DEFAULT_BASE_URL)
    }

    pub fn with_base_url(base_url: &str) -> Result<Self, FunPayError> {
        let client = Client::builder()
            .user_agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
            .cookie_store(true)
            .timeout(std::time::Duration::from_secs(30))
            .build()?;
        Ok(Self { client, base_url: base_url.to_string() })
    }

    pub async fn get(&self, path: &str) -> Result<String, FunPayError> {
        let url = if path.starts_with("http") {
            path.to_string()
        } else {
            format!("{}{}", self.base_url, path)
        };
        let resp = self.client.get(&url).send().await?;
        Ok(resp.text().await?)
    }

    pub async fn fetch_seller_profile(&self, seller_id: u64) -> Result<Seller, FunPayError> {
        let html = self.get(&format!("/users/{}/", seller_id)).await?;
        Parser::new().parse_seller_profile(&html).ok_or_else(|| FunPayError::Parse(crate::error::ParseError::MissingField("Seller".into())))
    }

    pub async fn fetch_chats(&self, ) -> Result<Vec<Chat>, FunPayError> {
        let html = self.get("/chats/").await?;
        Ok(Parser::new().parse_chats(&html))
    }

    pub async fn fetch_category_offers(&self, game_id: u64, category_id: u64) -> Result<Vec<Offer>, FunPayError> {
        let html = self.get(&format!("/lots/{}/{}/", game_id, category_id)).await?;
        Ok(Parser::new().parse_category_offers(&html))
    }

    pub async fn fetch_game_list(&self, ) -> Result<Vec<Game>, FunPayError> {
        let html = self.get("/lots/").await?;
        Ok(Parser::new().parse_game_list(&html))
    }

    pub async fn fetch_user_profile(&self, user_id: u64) -> Result<User, FunPayError> {
        let html = self.get(&format!("/users/{}/", user_id)).await?;
        Parser::new().parse_user_profile(&html).ok_or_else(|| FunPayError::Parse(crate::error::ParseError::MissingField("User".into())))
    }

    pub async fn fetch_chat_messages(&self, chat_id: u64) -> Result<Vec<ChatMessage>, FunPayError> {
        let html = self.get(&format!("/chats/{}/", chat_id)).await?;
        Ok(Parser::new().parse_chat_messages(&html))
    }

    pub async fn fetch_user_offers(&self, user_id: u64) -> Result<Vec<OfferLot>, FunPayError> {
        let html = self.get(&format!("/users/{}/lots/", user_id)).await?;
        Ok(Parser::new().parse_user_offers(&html))
    }

    pub async fn fetch_orders(&self, ) -> Result<Vec<Order>, FunPayError> {
        let html = self.get("/orders/").await?;
        Ok(Parser::new().parse_orders(&html))
    }

}
