// @generated by funpay-codegen — DO NOT EDIT

use serde::{Deserialize, Serialize};
use std::hash::Hash;


pub trait IdType: std::fmt::Display + std::str::FromStr + Clone + Copy + PartialEq + Eq + Hash {
    fn new(id: u64) -> Self;
    fn inner(self) -> u64;
}

macro_rules! define_id_type {
    ($name:ident) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
        pub struct $name(u64);

        impl $name {
            pub fn new(id: u64) -> Self { Self(id) }
            pub fn inner(self) -> u64 { self.0 }
        }

        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "{}", self.0)
            }
        }

        impl std::str::FromStr for $name {
            type Err = std::num::ParseIntError;
            fn from_str(s: &str) -> Result<Self, Self::Err> { Ok(Self(s.parse()?)) }
        }
    };
}

define_id_type!(OfferId);
define_id_type!(UserId);
define_id_type!(LotId);
define_id_type!(GameId);

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Server(pub String);

impl Server {
    pub fn new(s: impl Into<String>) -> Self { Self(s.into()) }
    pub fn inner(&self) -> &str { &self.0 }
}

impl std::fmt::Display for Server {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

pub type Timestamp = String;
pub type Price = f64;
pub type Url = String;
pub type Currency = String;

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum OfferOrderType {
    #[default]
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "manual")]
    Manual,
}

impl std::fmt::Display for OfferOrderType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            OfferOrderType::Auto => write!(f, "auto"),
            OfferOrderType::Manual => write!(f, "manual"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum LotSaleType {
    #[default]
    #[serde(rename = "single")]
    Single,
    #[serde(rename = "bulk")]
    Bulk,
}

impl std::fmt::Display for LotSaleType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LotSaleType::Single => write!(f, "single"),
            LotSaleType::Bulk => write!(f, "bulk"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum OrderStatus {
    #[default]
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "disputed")]
    Disputed,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "cancelled")]
    Cancelled,
}

impl std::fmt::Display for OrderStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            OrderStatus::Pending => write!(f, "pending"),
            OrderStatus::Completed => write!(f, "completed"),
            OrderStatus::Disputed => write!(f, "disputed"),
            OrderStatus::Active => write!(f, "active"),
            OrderStatus::Cancelled => write!(f, "cancelled"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum ServerTagType {
    #[default]
    #[serde(rename = "server")]
    Server,
    #[serde(rename = "platform")]
    Platform,
}

impl std::fmt::Display for ServerTagType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ServerTagType::Server => write!(f, "server"),
            ServerTagType::Platform => write!(f, "platform"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum OnlineStatus {
    #[default]
    #[serde(rename = "offline")]
    Offline,
    #[serde(rename = "online")]
    Online,
}

impl std::fmt::Display for OnlineStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            OnlineStatus::Offline => write!(f, "offline"),
            OnlineStatus::Online => write!(f, "online"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Lot {
    pub seller: Seller,
    pub description: Option<String>,
    pub id: String,
    pub server: Option<String>,
    pub price: Price,
    pub currency: Currency,
    pub game: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Order {
    pub price: Price,
    pub status: OrderStatus,
    pub date: Option<Timestamp>,
    pub order_id: String,
    pub seller: Seller,
    pub buyer: Seller,
    pub game: Option<String>,
    pub currency: Currency,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OfferLot {
    pub offer_id: OfferId,
    pub description: Option<String>,
    pub price: Price,
    pub server: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Seller {
    pub avatar_url: Url,
    pub name: String,
    pub reviews: u32,
    pub online: OnlineStatus,
    pub user_id: UserId,
    pub rating: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LotItem {
    pub id: String,
    pub name: String,
    pub image_url: Option<Url>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Chat {
    pub user: Seller,
    pub last_message: Option<String>,
    pub chat_id: String,
    pub unread_count: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GameCategory {
    pub name: String,
    pub url: Url,
    pub id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Game {
    pub url: Url,
    pub icon_url: Url,
    pub id: String,
    pub title: String,
    pub categories: Vec<Category>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Offer {
    pub price: Price,
    pub id: OfferId,
    pub server: Option<String>,
    pub description: Option<String>,
    pub currency: Currency,
    pub seller_id: UserId,
    pub sale_type: LotSaleType,
    pub item_count: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    pub sender: UserId,
    pub text: String,
    pub is_self: bool,
    pub date: Option<Timestamp>,
    pub message_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Category {
    pub url: Url,
    pub id: String,
    pub title: String,
    pub game_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    pub avatar_url: Url,
    pub username: String,
    pub status: Option<String>,
    pub id: UserId,
    pub registration_date: Option<Timestamp>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Review {
    pub author: Seller,
    pub text: Option<String>,
    pub date: Option<Timestamp>,
    pub rating: f64,
    pub review_id: String,
    pub order_link: Option<String>,
}

