// @generated by specgen — DO NOT EDIT

use serde::{Deserialize, Serialize};
use std::hash::Hash;

pub trait IdType: std::fmt::Display + std::str::FromStr + Clone + Copy + PartialEq + Eq + Hash {
    fn new(id: u64) -> Self;
    fn inner(self) -> u64;
}

macro_rules! define_id_type {
    ($name:ident) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
        pub struct $name(u64);

        impl $name {
            pub fn new(id: u64) -> Self { Self(id) }
            pub fn inner(self) -> u64 { self.0 }
        }

        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "{}", self.0)
            }
        }

        impl std::str::FromStr for $name {
            type Err = std::num::ParseIntError;
            fn from_str(s: &str) -> Result<Self, Self::Err> { Ok(Self(s.parse()?)) }
        }
    };
}

define_id_type!(UserId);
define_id_type!(GameId);
define_id_type!(LotId);
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Price(pub f64);

impl Price {
    pub fn new(v: impl Into<f64>) -> Self { Self(v.into()) }
    pub fn inner(&self) -> &f64 { &self.0 }
}

impl std::fmt::Display for Price {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl Default for Price {
    fn default() -> Self { Self(0.0) }
}

impl std::str::FromStr for Price {
    type Err = std::num::ParseFloatError;
    fn from_str(s: &str) -> Result<Self, Self::Err> { Ok(Self(s.parse()?)) }
}

define_id_type!(OfferId);

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum OrderStatus {
    #[default]
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "disputed")]
    Disputed,
}

impl std::fmt::Display for OrderStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            OrderStatus::Pending => write!(f, "pending"),
            OrderStatus::Completed => write!(f, "completed"),
            OrderStatus::Active => write!(f, "active"),
            OrderStatus::Cancelled => write!(f, "cancelled"),
            OrderStatus::Disputed => write!(f, "disputed"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum OnlineStatus {
    #[default]
    #[serde(rename = "online")]
    Online,
    #[serde(rename = "offline")]
    Offline,
}

impl std::fmt::Display for OnlineStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            OnlineStatus::Online => write!(f, "online"),
            OnlineStatus::Offline => write!(f, "offline"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum OfferOrderType {
    #[default]
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "manual")]
    Manual,
}

impl std::fmt::Display for OfferOrderType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            OfferOrderType::Auto => write!(f, "auto"),
            OfferOrderType::Manual => write!(f, "manual"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum ServerTagType {
    #[default]
    #[serde(rename = "platform")]
    Platform,
    #[serde(rename = "server")]
    Server,
}

impl std::fmt::Display for ServerTagType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ServerTagType::Platform => write!(f, "platform"),
            ServerTagType::Server => write!(f, "server"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum LotSaleType {
    #[default]
    #[serde(rename = "bulk")]
    Bulk,
    #[serde(rename = "single")]
    Single,
}

impl std::fmt::Display for LotSaleType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LotSaleType::Bulk => write!(f, "bulk"),
            LotSaleType::Single => write!(f, "single"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Lot {
    pub price: Price,
    pub game: Option<String>,
    pub server: Option<String>,
    pub id: String,
    pub seller: Seller,
    pub currency: String,
    pub description: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Order {
    pub game: Option<String>,
    pub date: Option<String>,
    pub order_id: String,
    pub seller: Seller,
    pub currency: String,
    pub status: OrderStatus,
    pub price: Price,
    pub buyer: Seller,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    pub text: String,
    pub sender: UserId,
    pub date: Option<String>,
    pub message_id: String,
    pub is_self: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GameCategory {
    pub id: String,
    pub name: String,
    pub url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LotItem {
    pub name: String,
    pub id: String,
    pub image_url: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Game {
    pub icon_url: String,
    pub title: String,
    pub categories: Vec<Category>,
    pub id: String,
    pub url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    pub username: String,
    pub status: Option<String>,
    pub avatar_url: String,
    pub id: UserId,
    pub registration_date: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Chat {
    pub last_message: Option<String>,
    pub unread_count: u32,
    pub chat_id: String,
    pub user: Seller,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Review {
    pub order_link: Option<String>,
    pub review_id: String,
    pub author: Seller,
    pub date: Option<String>,
    pub rating: f64,
    pub text: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OfferLot {
    pub offer_id: OfferId,
    pub server: Option<String>,
    pub description: Option<String>,
    pub price: Price,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Category {
    pub url: String,
    pub title: String,
    pub game_id: Option<String>,
    pub id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Seller {
    pub user_id: UserId,
    pub name: String,
    pub rating: f64,
    pub online: OnlineStatus,
    pub reviews: u32,
    pub avatar_url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Offer {
    pub item_count: Option<u32>,
    pub currency: String,
    pub seller_id: UserId,
    pub server: Option<String>,
    pub id: OfferId,
    pub price: Price,
    pub sale_type: LotSaleType,
    pub description: Option<String>,
}

