// @generated by funpay-codegen — DO NOT EDIT

use scraper::{Html, Selector};
use crate::models::*;

fn extract_text(el: &scraper::ElementRef, selector: &str) -> Option<String> {
    let sel = Selector::parse(selector).ok()?;
    el.select(&sel).next()?.text().next().map(|s| s.trim().to_string())
}

fn extract_attr(el: &scraper::ElementRef, selector: &str, attr: &str) -> Option<String> {
    let sel = Selector::parse(selector).ok()?;
    el.select(&sel).next()?.value().attr(attr).map(|s| s.to_string())
}

pub struct Parser;

impl Parser {
    pub fn new() -> Self { Self }
    pub fn parse_orders(&self, html: &str) -> Vec<Order> {
        let document = Html::parse_document(html);
        let selector = Selector::parse(".order-item").unwrap();
        document.select(&selector)
            .filter_map(|el| {
                let price = extract_text(&el, ".order-price");
                let status = extract_text(&el, ".order-status");
                let date = extract_text(&el, ".order-date");
                let order_id = extract_attr(&el, ".order-item", "data-order-id").unwrap_or_default();
                let seller = Seller { avatar_url: String::new(), name: String::new(), reviews: 0u32, online: Default::default(), user_id: UserId::new(0), rating: 0.0 };
                let buyer = Seller { avatar_url: String::new(), name: String::new(), reviews: 0u32, online: Default::default(), user_id: UserId::new(0), rating: 0.0 };
                let game = extract_text(&el, ".order-game");
                let currency = extract_text(&el, ".order-price .currency").unwrap_or_default();
                Some(Order {
                    price: price.and_then(|s| s.parse::<Price>().ok()).unwrap_or_default(),
                    status: status.and_then(|s| match s.as_str() { "pending" => Some(OrderStatus::Pending), "completed" => Some(OrderStatus::Completed), "disputed" => Some(OrderStatus::Disputed), "active" => Some(OrderStatus::Active), "cancelled" => Some(OrderStatus::Cancelled), _ => None }).unwrap_or_default(),
                    date,
                    order_id,
                    seller,
                    buyer,
                    game,
                    currency,
                })
            })
            .collect()
    }

    pub fn parse_game_list(&self, html: &str) -> Vec<Game> {
        let document = Html::parse_document(html);
        let selector = Selector::parse(".game-list .game-title").unwrap();
        document.select(&selector)
            .filter_map(|el| {
                let url = extract_attr(&el, "a.game-title", "href").unwrap_or_default();
                let icon_url = extract_attr(&el, "img.game-icon", "src").unwrap_or_default();
                let id = extract_attr(&el, "a.game-title", "data-game-id").unwrap_or_default();
                let title = extract_text(&el, "a.game-title").unwrap_or_default();
                let categories = Vec::new();
                Some(Game {
                    url,
                    icon_url,
                    id,
                    title,
                    categories,
                })
            })
            .collect()
    }

    pub fn parse_chats(&self, html: &str) -> Vec<Chat> {
        let document = Html::parse_document(html);
        let selector = Selector::parse(".chat-item").unwrap();
        document.select(&selector)
            .filter_map(|el| {
                let user = Seller { avatar_url: String::new(), name: String::new(), reviews: 0u32, online: Default::default(), user_id: UserId::new(0), rating: 0.0 };
                let last_message = extract_text(&el, ".chat-last-message");
                let chat_id = extract_attr(&el, ".chat-item", "data-chat-id").unwrap_or_default();
                let unread_count = extract_text(&el, ".chat-unread");
                Some(Chat {
                    user,
                    last_message,
                    chat_id,
                    unread_count: unread_count.and_then(|s| s.parse::<u32>().ok()).unwrap_or_default(),
                })
            })
            .collect()
    }

    pub fn parse_chat_messages(&self, html: &str) -> Vec<ChatMessage> {
        let document = Html::parse_document(html);
        let selector = Selector::parse(".msg").unwrap();
        document.select(&selector)
            .filter_map(|el| {
                let sender = extract_attr(&el, ".msg", "data-sender-id");
                let text = extract_text(&el, ".msg-text").unwrap_or_default();
                let is_self = extract_attr(&el, ".msg", "data-self");
                let date = extract_text(&el, ".msg-date");
                let message_id = extract_attr(&el, ".msg", "data-msg-id").unwrap_or_default();
                Some(ChatMessage {
                    sender: sender.and_then(|s| s.parse::<UserId>().ok()).unwrap_or_default(),
                    text,
                    is_self: is_self.and_then(|s| s.parse::<bool>().ok()).unwrap_or_default(),
                    date,
                    message_id,
                })
            })
            .collect()
    }

    pub fn parse_user_offers(&self, html: &str) -> Vec<OfferLot> {
        let document = Html::parse_document(html);
        let selector = Selector::parse(".tc-item").unwrap();
        document.select(&selector)
            .filter_map(|el| {
                let offer_id = extract_attr(&el, ".tc-item", "data-order");
                let description = extract_text(&el, ".tc-desc-text");
                let price = extract_text(&el, ".tc-price");
                let server = extract_text(&el, ".tc-server");
                Some(OfferLot {
                    offer_id: offer_id.and_then(|s| s.parse::<OfferId>().ok()).unwrap_or_default(),
                    description,
                    price: price.and_then(|s| s.parse::<Price>().ok()).unwrap_or_default(),
                    server,
                })
            })
            .collect()
    }

    pub fn parse_category_offers(&self, html: &str) -> Vec<Offer> {
        let document = Html::parse_document(html);
        let selector = Selector::parse(".tc-item").unwrap();
        document.select(&selector)
            .filter_map(|el| {
                let price = extract_text(&el, ".tc-price");
                let id = extract_attr(&el, ".tc-item", "data-order");
                let server = extract_text(&el, ".tc-server");
                let description = extract_text(&el, ".tc-desc-text");
                let currency = extract_text(&el, ".tc-price .currency").unwrap_or_default();
                let seller_id = extract_attr(&el, ".tc-item", "data-user-id");
                let sale_type = extract_attr(&el, ".tc-item", "data-mark");
                let item_count = extract_attr(&el, ".tc-item", "data lot-size");
                Some(Offer {
                    price: price.and_then(|s| s.parse::<Price>().ok()).unwrap_or_default(),
                    id: id.and_then(|s| s.parse::<OfferId>().ok()).unwrap_or_default(),
                    server,
                    description,
                    currency,
                    seller_id: seller_id.and_then(|s| s.parse::<UserId>().ok()).unwrap_or_default(),
                    sale_type: sale_type.and_then(|s| match s.as_str() { "single" => Some(LotSaleType::Single), "bulk" => Some(LotSaleType::Bulk), _ => None }).unwrap_or_default(),
                    item_count: item_count.and_then(|s| s.parse::<u32>().ok()),
                })
            })
            .collect()
    }

    pub fn parse_seller_profile(&self, html: &str) -> Option<Seller> {
        let document = Html::parse_document(html);
        let el = document.root_element();
        let avatar_url = extract_attr(&el, ".seller-avatar img", "src").unwrap_or_default();
        let name = extract_text(&el, ".seller-info .seller-name").unwrap_or_default();
        let reviews = extract_text(&el, ".seller-reviews");
        let online = extract_text(&el, ".seller-online");
        let user_id = extract_attr(&el, ".seller-info", "data-user-id");
        let rating = extract_text(&el, ".seller-rating");
        Some(Seller {
            avatar_url,
            name,
            reviews: reviews.and_then(|s| s.parse::<u32>().ok()).unwrap_or_default(),
            online: online.and_then(|s| match s.as_str() { "offline" => Some(OnlineStatus::Offline), "online" => Some(OnlineStatus::Online), _ => None }).unwrap_or_default(),
            user_id: user_id.and_then(|s| s.parse::<UserId>().ok()).unwrap_or_default(),
            rating: rating.and_then(|s| s.parse::<f64>().ok()).unwrap_or_default(),
        })
    }

    pub fn parse_user_profile(&self, html: &str) -> Option<User> {
        let document = Html::parse_document(html);
        let el = document.root_element();
        let avatar_url = extract_attr(&el, ".profile-avatar img", "src").unwrap_or_default();
        let username = extract_text(&el, ".profile-title").unwrap_or_default();
        let status = extract_text(&el, ".user-status");
        let id = extract_attr(&el, ".profile-user-id", "data-user-id");
        let registration_date = extract_text(&el, ".profile-regdate");
        Some(User {
            avatar_url,
            username,
            status,
            id: id.and_then(|s| s.parse::<UserId>().ok()).unwrap_or_default(),
            registration_date,
        })
    }

}
